//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"text/template"
)

func main() {
	// Parse the input file that contains the struct
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, os.Args[1], nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing file: %v\n", err)
		os.Exit(1)
	}
	var generateNewSDO bool
	var generateNewSRO bool
	if len(os.Args) >= 3 {
		if os.Args[2] == "sdo" {
			generateNewSDO = true
		}
		if os.Args[2] == "sro" {
			generateNewSRO = true
		}
	}

	// Find structs in the file
	structs := make(map[string]*ast.StructType)
	ast.Inspect(node, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok || typeSpec.Type == nil {
			return true
		}

		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		structs[typeSpec.Name.Name] = structType
		return true
	})
	// Generate code for each struct
	for structName, structType := range structs {
		fmt.Printf("Structname: %s \n", structName)
		generateCodeForStruct(os.Args[1], structName, structType, node.Name.Name, generateNewSDO, generateNewSRO)
	}

}

func generateCodeForStruct(fileName string, structName string, structType *ast.StructType, packageName string, generateNewSDO bool, generateNewSRO bool) {
	// Extract field information
	var fields []FieldInfo
	var usesTime bool
	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue // Skip embedded fields
		}

		fieldName := field.Names[0].Name
		fieldType := types.ExprString(field.Type)

		if fieldType == "time.Time" {
			usesTime = true
		}

		fmt.Println(fieldName + ": " + fieldType)

		fields = append(fields, FieldInfo{
			Name: fieldName,
			Type: fieldType,
		})
	}

	if generateNewSDO == true {
		usesTime = true
	}

	// Execute the template
	tmpl := template.Must(template.New("struct_code").Parse(baseTemplate))

	outputFile := fmt.Sprintf("%s_gen.go", fileName)
	f, err := os.Create(outputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	err = tmpl.Execute(f, TemplateData{
		PackageName:    packageName,
		StructName:     structName,
		Fields:         fields,
		UsesTime:       usesTime,
		GenerateNewSDO: generateNewSDO,
		GenerateNewSRO: generateNewSRO,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated code for struct %s in %s\n", structName, outputFile)
}

type FieldInfo struct {
	Name string
	Type string
}

type TemplateData struct {
	PackageName    string
	StructName     string
	UsesTime       bool
	GenerateNewSDO bool
	GenerateNewSRO bool
	Fields         []FieldInfo
}

// Template for the generated code
const baseTemplate = `// Code generated by generator; DO NOT EDIT.
package {{.PackageName}}

import (
	"encoding/json"
	{{if .UsesTime}}"time"{{end}}
	"github.com/go-playground/validator"
)


func (obj *{{.StructName}}) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *{{.StructName}}) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *{{.StructName}}) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type {{.StructName}}Option func(*{{.StructName}})

{{$struct := .StructName}}
{{range .Fields}}
func With{{$struct}}{{.Name}}(value {{.Type}}) {{$struct}}Option {
	return func(obj *{{$struct}}) {
		obj.{{.Name}} = value
	}
}
{{end}}

{{if .GenerateNewSDO}}

func (obj *{{.StructName}}) GetID() string {
	return obj.ID
}

func (obj *{{.StructName}}) GetType() string {
	return obj.Type
}

func (obj *{{.StructName}}) GetSpecVersion() string {
	return obj.SpecVersion
}

func (obj *{{.StructName}}) GetCreated() time.Time {
	return obj.Created
}

func (obj *{{.StructName}}) GetModified() time.Time {
	return obj.Modified
}

func New{{.StructName}}(sdoOptions []SDOOption, options []{{.StructName}}Option) *{{.StructName}} {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "{{.StructName}}",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &{{.StructName}}{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}
{{end}}

{{if .GenerateNewSRO}}
func New{{.StructName}}(sroOptions []SROOption, options []{{.StructName}}Option) *{{.StructName}} {
	now := time.Now()

	// Create base SDO with required fields
	sro := SRO{
		Type:        "{{.StructName}}",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	// Apply SDO options
	applySROOptions(&sro, sroOptions)

	// Create Relationship with embedded SDO
	obj := &{{.StructName}}{
		SRO: sro,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}
{{end}}
`
