// Code generated by generator; DO NOT EDIT.
package main

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *Identity) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *Identity) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *Identity) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type IdentityOption func(*Identity)



func WithIdentityName(value string) IdentityOption {
	return func(obj *Identity) {
		obj.Name = value
	}
}

func WithIdentityDescription(value string) IdentityOption {
	return func(obj *Identity) {
		obj.Description = value
	}
}

func WithIdentityRoles(value []string) IdentityOption {
	return func(obj *Identity) {
		obj.Roles = value
	}
}

func WithIdentityIdentityClass(value string) IdentityOption {
	return func(obj *Identity) {
		obj.IdentityClass = value
	}
}

func WithIdentitySectors(value []string) IdentityOption {
	return func(obj *Identity) {
		obj.Sectors = value
	}
}

func WithIdentityContactInformation(value string) IdentityOption {
	return func(obj *Identity) {
		obj.ContactInformation = value
	}
}



func NewIdentity(sdoOptions []SDOOption, options []IdentityOption) *Identity {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "Identity",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &Identity{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



