// Code generated by generator; DO NOT EDIT.
package main

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *Relationship) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *Relationship) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *Relationship) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type RelationshipOption func(*Relationship)



func WithRelationshipType(value string) RelationshipOption {
	return func(obj *Relationship) {
		obj.Type = value
	}
}

func WithRelationshipDescription(value string) RelationshipOption {
	return func(obj *Relationship) {
		obj.Description = value
	}
}

func WithRelationshipSourceRef(value string) RelationshipOption {
	return func(obj *Relationship) {
		obj.SourceRef = value
	}
}

func WithRelationshipTargetRef(value string) RelationshipOption {
	return func(obj *Relationship) {
		obj.TargetRef = value
	}
}

func WithRelationshipStartTime(value time.Time) RelationshipOption {
	return func(obj *Relationship) {
		obj.StartTime = value
	}
}

func WithRelationshipStopTime(value time.Time) RelationshipOption {
	return func(obj *Relationship) {
		obj.StopTime = value
	}
}





func NewRelationship(sroOptions []SROOption, options []RelationshipOption) *Relationship {
	now := time.Now()

	// Create base SDO with required fields
	sro := SRO{
		Type:        "Relationship",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	// Apply SDO options
	applySROOptions(&sro, sroOptions)

	// Create Relationship with embedded SDO
	obj := &Relationship{
		SRO: sro,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}

