// Code generated by generator; DO NOT EDIT.
package main

import (
	"encoding/json"
	
	"github.com/go-playground/validator"
)


func (obj *SCO) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *SCO) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *SCO) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type SCOOption func(*SCO)



func WithSCOType(value string) SCOOption {
	return func(obj *SCO) {
		obj.Type = value
	}
}

func WithSCOSpecVersion(value string) SCOOption {
	return func(obj *SCO) {
		obj.SpecVersion = value
	}
}

func WithSCOID(value string) SCOOption {
	return func(obj *SCO) {
		obj.ID = value
	}
}

func WithSCOObjectMarkingRefs(value []string) SCOOption {
	return func(obj *SCO) {
		obj.ObjectMarkingRefs = value
	}
}

func WithSCOGranularMarkings(value []string) SCOOption {
	return func(obj *SCO) {
		obj.GranularMarkings = value
	}
}





