// Code generated by generator; DO NOT EDIT.
package main

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *ThreatActor) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *ThreatActor) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *ThreatActor) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type ThreatActorOption func(*ThreatActor)



func WithThreatActorName(value string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.Name = value
	}
}

func WithThreatActorDescription(value string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.Description = value
	}
}

func WithThreatActorTypes(value []string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.Types = value
	}
}

func WithThreatActorAliases(value []string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.Aliases = value
	}
}

func WithThreatActorFirstSeen(value time.Time) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.FirstSeen = value
	}
}

func WithThreatActorLastSeen(value time.Time) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.LastSeen = value
	}
}

func WithThreatActorRoles(value []string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.Roles = value
	}
}

func WithThreatActorGoals(value []string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.Goals = value
	}
}

func WithThreatActorSophistication(value string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.Sophistication = value
	}
}

func WithThreatActorResourceLevel(value string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.ResourceLevel = value
	}
}

func WithThreatActorPrimaryMotivation(value string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.PrimaryMotivation = value
	}
}

func WithThreatActorSecondaryMotivation(value []string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.SecondaryMotivation = value
	}
}

func WithThreatActorPersonalMotivation(value []string) ThreatActorOption {
	return func(obj *ThreatActor) {
		obj.PersonalMotivation = value
	}
}



func NewThreatActor(sdoOptions []SDOOption, options []ThreatActorOption) *ThreatActor {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "ThreatActor",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &ThreatActor{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



