// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	
	"github.com/go-playground/validator"
)


func (obj *AttackPattern) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *AttackPattern) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *AttackPattern) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type AttackPatternOption func(*AttackPattern)



func WithAttackPatternName(value string) AttackPatternOption {
	return func(obj *AttackPattern) {
		obj.Name = value
	}
}

func WithAttackPatternDescription(value string) AttackPatternOption {
	return func(obj *AttackPattern) {
		obj.Description = value
	}
}

func WithAttackPatternAliases(value []string) AttackPatternOption {
	return func(obj *AttackPattern) {
		obj.Aliases = value
	}
}

func WithAttackPatternKillChainPhases(value []string) AttackPatternOption {
	return func(obj *AttackPattern) {
		obj.KillChainPhases = value
	}
}





