// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *AttackPattern) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *AttackPattern) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *AttackPattern) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type AttackPatternOption func(*AttackPattern)



func WithAttackPatternName(value string) AttackPatternOption {
	return func(obj *AttackPattern) {
		obj.Name = value
	}
}

func WithAttackPatternDescription(value string) AttackPatternOption {
	return func(obj *AttackPattern) {
		obj.Description = value
	}
}

func WithAttackPatternAliases(value []string) AttackPatternOption {
	return func(obj *AttackPattern) {
		obj.Aliases = value
	}
}

func WithAttackPatternKillChainPhases(value []string) AttackPatternOption {
	return func(obj *AttackPattern) {
		obj.KillChainPhases = value
	}
}




func (obj *AttackPattern) SetID(id string) {
	obj.ID = id
}

func (obj *AttackPattern) GetID() string {
	return obj.ID
}

func (obj *AttackPattern) GetType() string {
	return obj.Type
}

func (obj *AttackPattern) GetSpecVersion() string {
	return obj.SpecVersion
}

func (obj *AttackPattern) GetCreated() time.Time {
	return obj.Created
}

func (obj *AttackPattern) GetModified() time.Time {
	return obj.Modified
}

func NewAttackPattern(sdoOptions []SDOOption, options []AttackPatternOption) *AttackPattern {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "AttackPattern",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &AttackPattern{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



