// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *Campaign) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *Campaign) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *Campaign) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type CampaignOption func(*Campaign)



func WithCampaignName(value string) CampaignOption {
	return func(obj *Campaign) {
		obj.Name = value
	}
}

func WithCampaignDescription(value string) CampaignOption {
	return func(obj *Campaign) {
		obj.Description = value
	}
}

func WithCampaignAliases(value []string) CampaignOption {
	return func(obj *Campaign) {
		obj.Aliases = value
	}
}

func WithCampaignFirstSeen(value time.Time) CampaignOption {
	return func(obj *Campaign) {
		obj.FirstSeen = value
	}
}

func WithCampaignLastSeen(value time.Time) CampaignOption {
	return func(obj *Campaign) {
		obj.LastSeen = value
	}
}

func WithCampaignObjective(value string) CampaignOption {
	return func(obj *Campaign) {
		obj.Objective = value
	}
}




func (obj *Campaign) GetID() string {
	return obj.ID
}

func (obj *Campaign) GetType() string {
	return obj.Type
}

func (obj *Campaign) GetSpecVersion() string {
	return obj.SpecVersion
}

func (obj *Campaign) GetCreated() time.Time {
	return obj.Created
}

func (obj *Campaign) GetModified() time.Time {
	return obj.Modified
}

func NewCampaign(sdoOptions []SDOOption, options []CampaignOption) *Campaign {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "Campaign",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &Campaign{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



