// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *CourseOfAction) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *CourseOfAction) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *CourseOfAction) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type CourseOfActionOption func(*CourseOfAction)



func WithCourseOfActionName(value string) CourseOfActionOption {
	return func(obj *CourseOfAction) {
		obj.Name = value
	}
}

func WithCourseOfActionDescription(value string) CourseOfActionOption {
	return func(obj *CourseOfAction) {
		obj.Description = value
	}
}

func WithCourseOfActionActionType(value []string) CourseOfActionOption {
	return func(obj *CourseOfAction) {
		obj.ActionType = value
	}
}

func WithCourseOfActionOsExecutionEnvs(value []string) CourseOfActionOption {
	return func(obj *CourseOfAction) {
		obj.OsExecutionEnvs = value
	}
}

func WithCourseOfActionActionBin(value string) CourseOfActionOption {
	return func(obj *CourseOfAction) {
		obj.ActionBin = value
	}
}

func WithCourseOfActionActionReference(value ExternalReference) CourseOfActionOption {
	return func(obj *CourseOfAction) {
		obj.ActionReference = value
	}
}




func (obj *CourseOfAction) GetID() string {
	return obj.ID
}

func (obj *CourseOfAction) GetType() string {
	return obj.Type
}

func (obj *CourseOfAction) GetSpecVersion() string {
	return obj.SpecVersion
}

func (obj *CourseOfAction) GetCreated() time.Time {
	return obj.Created
}

func (obj *CourseOfAction) GetModified() time.Time {
	return obj.Modified
}

func NewCourseOfAction(sdoOptions []SDOOption, options []CourseOfActionOption) *CourseOfAction {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "CourseOfAction",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &CourseOfAction{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



