// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *ExternalReference) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *ExternalReference) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *ExternalReference) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type ExternalReferenceOption func(*ExternalReference)



func WithExternalReferenceSourceName(value string) ExternalReferenceOption {
	return func(obj *ExternalReference) {
		obj.SourceName = value
	}
}

func WithExternalReferenceExternalID(value string) ExternalReferenceOption {
	return func(obj *ExternalReference) {
		obj.ExternalID = value
	}
}



func NewExternalReference(sdoOptions []SDOOption, options []ExternalReferenceOption) *ExternalReference {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "ExternalReference",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &ExternalReference{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



