// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *Grouping) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *Grouping) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *Grouping) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type GroupingOption func(*Grouping)



func WithGroupingName(value string) GroupingOption {
	return func(obj *Grouping) {
		obj.Name = value
	}
}

func WithGroupingDescription(value string) GroupingOption {
	return func(obj *Grouping) {
		obj.Description = value
	}
}

func WithGroupingContext(value []string) GroupingOption {
	return func(obj *Grouping) {
		obj.Context = value
	}
}

func WithGroupingObjectRefs(value []string) GroupingOption {
	return func(obj *Grouping) {
		obj.ObjectRefs = value
	}
}




func (obj *Grouping) SetID(id string) {
	obj.ID = id
}

func (obj *Grouping) GetID() string {
	return obj.ID
}

func (obj *Grouping) GetType() string {
	return obj.Type
}

func (obj *Grouping) GetSpecVersion() string {
	return obj.SpecVersion
}

func (obj *Grouping) GetCreated() time.Time {
	return obj.Created
}

func (obj *Grouping) GetModified() time.Time {
	return obj.Modified
}

func NewGrouping(sdoOptions []SDOOption, options []GroupingOption) *Grouping {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "Grouping",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &Grouping{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



