// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *Indicator) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *Indicator) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *Indicator) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type IndicatorOption func(*Indicator)



func WithIndicatorName(value string) IndicatorOption {
	return func(obj *Indicator) {
		obj.Name = value
	}
}

func WithIndicatorDescription(value string) IndicatorOption {
	return func(obj *Indicator) {
		obj.Description = value
	}
}

func WithIndicatorTypes(value []string) IndicatorOption {
	return func(obj *Indicator) {
		obj.Types = value
	}
}

func WithIndicatorPattern(value string) IndicatorOption {
	return func(obj *Indicator) {
		obj.Pattern = value
	}
}

func WithIndicatorPatternType(value string) IndicatorOption {
	return func(obj *Indicator) {
		obj.PatternType = value
	}
}

func WithIndicatorPatternVersion(value string) IndicatorOption {
	return func(obj *Indicator) {
		obj.PatternVersion = value
	}
}

func WithIndicatorValidFrom(value time.Time) IndicatorOption {
	return func(obj *Indicator) {
		obj.ValidFrom = value
	}
}

func WithIndicatorValidUntil(value time.Time) IndicatorOption {
	return func(obj *Indicator) {
		obj.ValidUntil = value
	}
}

func WithIndicatorKillChainPhases(value []string) IndicatorOption {
	return func(obj *Indicator) {
		obj.KillChainPhases = value
	}
}




func (obj *Indicator) GetID() string {
	return obj.ID
}

func (obj *Indicator) GetType() string {
	return obj.Type
}

func (obj *Indicator) GetSpecVersion() string {
	return obj.SpecVersion
}

func (obj *Indicator) GetCreated() time.Time {
	return obj.Created
}

func (obj *Indicator) GetModified() time.Time {
	return obj.Modified
}

func NewIndicator(sdoOptions []SDOOption, options []IndicatorOption) *Indicator {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "Indicator",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &Indicator{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



