// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *Infrastructure) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *Infrastructure) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *Infrastructure) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type InfrastructureOption func(*Infrastructure)



func WithInfrastructureName(value string) InfrastructureOption {
	return func(obj *Infrastructure) {
		obj.Name = value
	}
}

func WithInfrastructureDescription(value string) InfrastructureOption {
	return func(obj *Infrastructure) {
		obj.Description = value
	}
}

func WithInfrastructureTypes(value []string) InfrastructureOption {
	return func(obj *Infrastructure) {
		obj.Types = value
	}
}

func WithInfrastructureAliases(value string) InfrastructureOption {
	return func(obj *Infrastructure) {
		obj.Aliases = value
	}
}

func WithInfrastructureKillChainPhases(value []string) InfrastructureOption {
	return func(obj *Infrastructure) {
		obj.KillChainPhases = value
	}
}

func WithInfrastructureFirstSeen(value time.Time) InfrastructureOption {
	return func(obj *Infrastructure) {
		obj.FirstSeen = value
	}
}

func WithInfrastructureLastSeen(value time.Time) InfrastructureOption {
	return func(obj *Infrastructure) {
		obj.LastSeen = value
	}
}




func (obj *Infrastructure) SetID(id string) {
	obj.ID = id
}

func (obj *Infrastructure) GetID() string {
	return obj.ID
}

func (obj *Infrastructure) GetType() string {
	return obj.Type
}

func (obj *Infrastructure) GetSpecVersion() string {
	return obj.SpecVersion
}

func (obj *Infrastructure) GetCreated() time.Time {
	return obj.Created
}

func (obj *Infrastructure) GetModified() time.Time {
	return obj.Modified
}

func NewInfrastructure(sdoOptions []SDOOption, options []InfrastructureOption) *Infrastructure {
	now := time.Now()

	// Create base SDO with required fields
	sdo := SDO{
		Type:        "Infrastructure",
		SpecVersion: "2.1", // Default version
		Created:     now,
		Modified:    now,
	}

	for _, option := range sdoOptions {
		option(&sdo)
	}

	obj := &Infrastructure{
		SDO: sdo,
	}

	for _, option := range options {
		option(obj)
	}

	return obj
}



