// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *SDO) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *SDO) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *SDO) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type SDOOption func(*SDO)



func WithSDOType(value string) SDOOption {
	return func(obj *SDO) {
		obj.Type = value
	}
}

func WithSDOSpecVersion(value string) SDOOption {
	return func(obj *SDO) {
		obj.SpecVersion = value
	}
}

func WithSDOID(value string) SDOOption {
	return func(obj *SDO) {
		obj.ID = value
	}
}

func WithSDOCreatedByRef(value bool) SDOOption {
	return func(obj *SDO) {
		obj.CreatedByRef = value
	}
}

func WithSDOCreated(value time.Time) SDOOption {
	return func(obj *SDO) {
		obj.Created = value
	}
}

func WithSDOModified(value time.Time) SDOOption {
	return func(obj *SDO) {
		obj.Modified = value
	}
}

func WithSDORevoked(value bool) SDOOption {
	return func(obj *SDO) {
		obj.Revoked = value
	}
}

func WithSDOLabels(value []string) SDOOption {
	return func(obj *SDO) {
		obj.Labels = value
	}
}

func WithSDOConfidence(value int) SDOOption {
	return func(obj *SDO) {
		obj.Confidence = value
	}
}

func WithSDOLang(value string) SDOOption {
	return func(obj *SDO) {
		obj.Lang = value
	}
}

func WithSDOExternalReferences(value []ExternalReference) SDOOption {
	return func(obj *SDO) {
		obj.ExternalReferences = value
	}
}

func WithSDOObjectMarkingRefs(value []string) SDOOption {
	return func(obj *SDO) {
		obj.ObjectMarkingRefs = value
	}
}

func WithSDOGranularMarkings(value []string) SDOOption {
	return func(obj *SDO) {
		obj.GranularMarkings = value
	}
}





