// Code generated by generator; DO NOT EDIT.
package stix

import (
	"encoding/json"
	"time"
	"github.com/go-playground/validator"
)


func (obj *SRO) Validate() error {
	validator := validator.New()
	return validator.Struct(obj)
}

// FromJSONBytes reads JSON from a byte slice into the struct
func (obj *SRO) FromJSONBytes(data []byte) error {
	if err := json.Unmarshal(data, obj); err != nil {
		return err
	}
	return obj.Validate()
}

// ToJSONBytes converts the struct to a JSON byte slice
func (d *SRO) ToJSONBytes() ([]byte, error) {
	return json.Marshal(d)
}

type SROOption func(*SRO)



func WithSROType(value string) SROOption {
	return func(obj *SRO) {
		obj.Type = value
	}
}

func WithSROSpecVersion(value string) SROOption {
	return func(obj *SRO) {
		obj.SpecVersion = value
	}
}

func WithSROID(value string) SROOption {
	return func(obj *SRO) {
		obj.ID = value
	}
}

func WithSROCreatedByRef(value bool) SROOption {
	return func(obj *SRO) {
		obj.CreatedByRef = value
	}
}

func WithSROCreated(value time.Time) SROOption {
	return func(obj *SRO) {
		obj.Created = value
	}
}

func WithSROModified(value time.Time) SROOption {
	return func(obj *SRO) {
		obj.Modified = value
	}
}

func WithSRORevoked(value bool) SROOption {
	return func(obj *SRO) {
		obj.Revoked = value
	}
}

func WithSROLabels(value []string) SROOption {
	return func(obj *SRO) {
		obj.Labels = value
	}
}

func WithSROConfidence(value int) SROOption {
	return func(obj *SRO) {
		obj.Confidence = value
	}
}

func WithSROLang(value string) SROOption {
	return func(obj *SRO) {
		obj.Lang = value
	}
}

func WithSROExternalReferences(value []ExternalReference) SROOption {
	return func(obj *SRO) {
		obj.ExternalReferences = value
	}
}

func WithSROObjectMarkingRefs(value []string) SROOption {
	return func(obj *SRO) {
		obj.ObjectMarkingRefs = value
	}
}

func WithSROGranularMarkings(value []string) SROOption {
	return func(obj *SRO) {
		obj.GranularMarkings = value
	}
}





